name: Verify

on: 
    push:
        branches: [ main ]

    pull_request:
        branches: [ main ]

jobs: 
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: use Node 20
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: install dependencies
              run: yarn install --frozen-lockfile 
            - name: build the app
              run: yarn run build